pyton:
  request_timeout: 20
  parallel_requests_per_liteserver: 50
  get_methods: true
  json_rpc: true
  liteserver_config: config/testnet.json
  keystore: ./ton_keystore/
  cdll: null
logs:
  successful_requests: true
cache:
  use_redis: true
mongodb:
  host: mongodb
  port: 27017
  database: pyton
  username: user1
  password_file: /run/secrets/mongodb_password
postgres:
  host: postgres
  port: 5432
  user: user1
  password_file: /run/secrets/postgres_password
  dbname: pyton
cache_redis:
  endpoint: cache_redis
  port: 6379
  timeout: 1
slowapi_redis:
  endpoint: slowapi_redis
  port: 6379
  timeout: 1
token_redis:
  endpoint: token_redis
  port: 6379
token_bot:
  token_file: /run/secrets/token_file
